// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhDFs_jVCIa1rovwjHr2Dw8GH3sKlreB4',
    appId: '1:484152610513:web:8615760c2f33473582bff0',
    messagingSenderId: '484152610513',
    projectId: 'buy-it-ec446',
    authDomain: 'buy-it-ec446.firebaseapp.com',
    storageBucket: 'buy-it-ec446.appspot.com',
    measurementId: 'G-WE2VNH60X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGKiaEnmSXNr4RLqDN3FgxeFeH_NjOFLs',
    appId: '1:484152610513:android:76874170b785299682bff0',
    messagingSenderId: '484152610513',
    projectId: 'buy-it-ec446',
    storageBucket: 'buy-it-ec446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMKPoD9mKpuA3GPyl4PXJxbq6EIg7ixrg',
    appId: '1:484152610513:ios:6eaea7a3e308147e82bff0',
    messagingSenderId: '484152610513',
    projectId: 'buy-it-ec446',
    storageBucket: 'buy-it-ec446.appspot.com',
    iosClientId: '484152610513-fjmq8pgdo3hm8d0723lm4t0l1f9oijni.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMKPoD9mKpuA3GPyl4PXJxbq6EIg7ixrg',
    appId: '1:484152610513:ios:d53fcaec56bd2ed382bff0',
    messagingSenderId: '484152610513',
    projectId: 'buy-it-ec446',
    storageBucket: 'buy-it-ec446.appspot.com',
    iosClientId: '484152610513-1nusi6dadfolf9bcg7f8tdmt02ds4opv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommapp.RunnerTests',
  );
}
